micronaut:
  application:
    name: neofloraRest
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
    - access: isAnonymous()
      pattern: /swagger/**
    - access: isAnonymous()
      pattern: /swagger-ui/**
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  caches:
    my-cache:
      maximumSize: 20
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
rabbitmq.uri: amqp://localhost:5672
